version: '3'

services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile

    ports:
      - "8000:8000"

    restart: always

  redis:
    image: redis:7

  postgres:
    image: postgres:15

    environment:
      POSTGRES_USER: quant
      POSTGRES_PASSWORD: quant123
